### ISSUE TITLE
Fix middleware not having a name in logs

### ISSUE THREAD

**Issue by AdamVig** [Juravenator/restify-json-hal#6]
![image](https://cloud.githubusercontent.com/assets/5354752/23664680/35deccfa-0324-11e7-989b-d0b32af4f7ea.png)
The `running ?` line in the screenshot above is caused by this library.

In `index.js`, [the main export](https://github.com/Juravenator/restify-json-hal/blob/master/index.js#L3) of the library should be
```JavaScript
module.exports = function restifyJSONHal(server, options) {
```
so that logs can show the name of the middleware as it processes each request.

**Comment by Juravenator** [comment]
I think the anonymous function there is actually the one on [line 26](https://github.com/Juravenator/restify-json-hal/blob/master/index.js#L26).

But the argument stands, I've used arrow functions way to much in this project.  
Basically, any arrow function that isn't a one-liner should be a named function.

**Comment by AdamVig** [comment]
You're absolutely right, I didn't read far enough down into that file!

I agree: I also prefer the syntax of arrow functions and am guilty of overusing them in my own projects.

**Comment by Juravenator** [comment]
I've opened a new branch [`named-functions`](https://github.com/Juravenator/restify-json-hal/tree/named-functions) for this.  
I edited the main file just now, others to follow.

**Comment by Juravenator** [comment]
I've merged `named-function` with `master` and tagged a new release. closing.
